# Generated by Django 4.0 on 2021-12-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_phone_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passWord',
            new_name='password',
        ),
    ]
